### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by JamesScreech** [brianlagunas/BindingEnumsInWpf#2]
This is a great solution to localising descriptions for enums when they are displayed, however the performance is not very good, is there anyway it can be improved?

**Comment by brianlagunas** [comment]
This is the approach I have always used and have not experienced any performance issues. I don’t know of another way off the top of my head. I’m sure there is another way, you’ll just need to find it.

**Comment by JamesScreech** [comment]
The issue appear to be related to creating a new instance of ResourceManager in the LocalizedDescriptionAttribute constructor. I'm thinking of caching them in a static collection for re-use.
